### ISSUE TITLE
Custom Serializer Errors

### ISSUE THREAD

**Issue by npickett** [nowol/DesertOctopus#12]
Having issues implementing a Custom Serializer. The below code works: 

            var config = new FirstLevelCacheConfig();
            // Objects will stay at most 20 seconds in the cache.  You will want to increase this value for your use case.
            config.AbsoluteExpiration = TimeSpan.FromSeconds(20);
            // The maximum memory allowed for the cache (in bytes)
            config.MaximumMemorySize = 1000;
            // Timer that cleanups the cache and remove object and the memory usage is greater than the maximum allowed
            config.TimerInterval = 60;
            // This cloning provider always cloned objects from the first level cache
            // Other providers available are NoCloningProvider and NamespacesBasedCloningProvider
            var cloningProvider = new AlwaysCloningProvider();
            var firstLevelCache = new SquirrelCache(config, cloningProvider);
            // Create a retry policy that will retry 3  times and it will wait 50ms, then 100ms and finally 150ms for each respective retries
            var redisRetryPolicy = new RedisRetryPolicy(50, 100, 150);
            // Create an instance of the Redis second level cache
            var secondLevelCache = new RedisConnection(connectionString, redisRetryPolicy);

            var binarySerializationProvider = new MammothCacheSerializationProvider(); //new BinarySerializationProvider();
            return new MammothCache(firstLevelCache, secondLevelCache, new NonSerializableCache(), binarySerializationProvider);

When I update the binarySerializationProvider to a non MammothCacheSerializationProvider concrete implementation, I get errors after exiting the IMammothCacheSerializationProvider.Serialize method is called:

var binarySerializationProvider = new BinarySerializationProvider();

I get this stack trace with exception message "Value cannot be null.\r\nParameter name: key”:

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at DesertOctopus.Utilities.SerializedTypeResolver.GetTypeFromFullName(String typeFullName)
   at DesertOctopus.Serialization.Deserializer.Deserialize(Byte[] bytes)
   at DesertOctopus.KrakenSerializer.Deserialize(Byte[] bytes)
   at DesertOctopus.MammothCache.SquirrelCache.CreateCachedObject(String key, Byte[] serializedValue)
   at DesertOctopus.MammothCache.SquirrelCache.Set(String key, Byte[] serializedValue, Nullable`1 ttl)
   at DesertOctopus.MammothCache.MammothCache.Set[T](String key, T value, Nullable`1 ttl)
   at POCRedis.Mammoth.MammothStore.Set[T](String key, T value) in C:\projects\POCs\POCRedis\POCRedis.Mammoth\MammothStore.cs:line 78
   at POCRedis.ConsoleApp.Program.SetValue(ICacheStore store, String key, String value) in C:\projects\POCs\POCRedis\POCRedis.ConsoleApp\Program.cs:line 40
   at POCRedis.ConsoleApp.Program.Main(String[] args) in C:\projects\POCs\POCRedis\POCRedis.ConsoleApp\Program.cs:line 29
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

When a colleague tried another binarySerializationProvider :

var binarySerializationProvider = new SharpSerializationProvider();

and got this stack trace with exception message:

at DesertOctopus.Serialization.Deserializer.ValidateHeader(MemoryStream ms, List`1 objs)
   at DesertOctopus.Serialization.Deserializer.Deserialize(Byte[] bytes)
   at DesertOctopus.MammothCache.SquirrelCache.CreateCachedObject(String key, Byte[] serializedValue)
   at DesertOctopus.MammothCache.SquirrelCache.Set(String key, Byte[] serializedValue, Nullable`1 ttl)
   at DesertOctopus.MammothCache.MammothCache.Set[T](String key, T value, Nullable`1 ttl)
   at POCRedis.Mammoth.MammothStore.Set[T](String key, T value) in C:\projects\POCRedis\POCRedis.Mammoth\MammothStore.cs:line 79
   at POCRedis.ConsoleApp.Program.SetValue(ICacheStore store, String key, String value) in C:\projects\POCRedis\POCRedis.ConsoleApp\Program.cs:line 40
   at POCRedis.ConsoleApp.Program.Main(String[] args) in C:\projects\POCRedis\POCRedis.ConsoleApp\Program.cs:line 29
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by nowol** [comment]
Oh, I see the issue.  I hardcoded the KrakenSerializer in that `IFirstLevelCache` implementation instead of using the serialization provider. 

Which serializer do you use inside your `BinarySerializationProvider` implementation? Is it Microsoft's BinaryFormatter? I was thinking of creating another implementation of `IMammothCacheSerializationProvider` that uses BinaryFormatter to unit test the issue and I could make it public if it's useful.

I'm also curious why you created your own `BinarySerializationProvider`.  Were you having issue with the built-in `MammothCacheSerializationProvider` that uses `KrakenSerializer`?

I'll answer your other questions here:

`1. Are there plans to support Sliding window expiration`

This feature is not supported by Redis so I cannot support it myself.  Well...there is a hackish way to achieve it but this is not something I want to support considering how brittle it would be. 

You can try asking for the feature here: https://github.com/antirez/redis/issues

```
If defaults are set for the following FirstLevelCacheConfig properties, what happens? No expiration?

*  Absolute
*  Max Memory
*  Timer Interval
```

Which defaults are you talking about?  If you don't specify any values for these properties I would expect (I didn't test it) that the first level cache would be disabled since the `MaximumMemorySize` would be 0 bytes. I'll add more validation to make sure the values are set to something.

The idea behind the first level cache is to provide a small in memory cache in front of Redis to have faster access to the stored items. A first level cache of 100mb is usually a good size depending on your workload.

What are your caching needs?  I could suggest sensible values if I know more about your usage.

`3. Do you have a Nuget Version with .Net 4.5?`

I should be able to change the .Net version to 4.5.2.

Give me a few days and I should be able to fix the bug and change the .Net version.

**Comment by npickett** [comment]
Thanks for the answers - MammothCacheSerializationProvider was working fine, I was using BinaryFormatter for testing out the custom serializer functionality.  No need to make it public on my account.

I will put in a request or vote up the sliding window feature for redis, thanks for clarifying.

For the defaults for FirstLevelCacheConfig properties, we were hoping that if defaults were set, local cache would be disabled. We have some cases that we would like to disable local cache to avoid out of date reads.  For example, when one Virtual Machine (VM 1) has a cache key/value pair cached locally and then another Virtual Machine (VM 2) sets a new value.  VM 1 could have an out of date read if set by VM 2 is within the local cache TTL of VM 1.

A .net 4.5.2 version would be great, thank you.

**Comment by nowol** [comment]
The best way to disable the first level cache would be to have your own implementation of `IFirstLevelCache` where you don't do anything in the methods.  I already use such a class for the unit tests and I can make it available if you want.

I do not think that you need to disable the first level cache since `MammothCache` is built to remove items from the first level cache if they are removed or modified in Redis.  This mechanism uses the keyspace notification and pubsub features or Redis.  You can enable the feature by putting the following line in your redis.conf or in the Azure Redis configuration UI.

```
notify-keyspace-events "Exeg"
```

**Comment by nowol** [comment]
Another option if you really do not need the first level cache would be to use `RedisConnection` from the `MammothCache.Redis` package directly instead of using `MammothCache`.

**Comment by npickett** [comment]
Ah, good point.  And for serialization, are you thinking just perform that outside of the library?

**Comment by nowol** [comment]
I'll include my `NullFirstLevelCache` implementation in the next version.

**Comment by nowol** [comment]
I published a new Nuget package with the following changes:

- Target .Net 4.5.2
- New `NullFirstLevelCache`
- More validation for `IFirstLevelCache`
- Small performance improvement in `KrakenSerializer`

Feel free to close this issue once you have tested the new version.

**Comment by nowol** [comment]
I published a new Nuget package with the following changes:

- Target .Net 4.5.2
- New `NullFirstLevelCache`
- More validation for `IFirstLevelCache`
- Small performance improvement in `KrakenSerializer`

Feel free to close this issue once you have tested the new version.
